### ISSUE TITLE
Atualizar e Revisar todos os diagramas

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#154]
### Descrição:
Após feedback da professora, revisar as tarefas a serem feitas e atualizar o diagrama que você e sua dupla fizeram.

---
#### Feedback (Daniel Porto, Eliseu Kadesh)

- [x] Melhorar o embasamento teórico;
- [x] Adicionar elos com artefatos;
- [x] Adicionar referências no texto;
- [ ] Revisar a semântica de agregação e associação;
- [ ] Melhorar o encaspulamento (Mudar alguns métodos de public para private);
- [ ] Adicionar rastros de debates em equipe;
- [ ] Verificar os links das referências

#### Adicionais
- [ ]  Adicionar classes e métodos que foram verificados em artefatos posteriores;

---

#### Feedback (Enzo Gabriel, Francisco Emanoel)
- [ ]  Detalhamento mais interno
- [ ] Nome dos pacotes devem ser minúculo
- [ ] Adicionar mais texto, complementando o nível de modelagem.
- [ ] Adicionar elos com outros aterfatos
- [ ] Rastros para debates de equipe
- [ ] Consertar links das referência quebrados.
- [ ] Adicionar mais referências .
- [ ]  Adicionar mais membros no versionamento
#### Adicionais
- [ ]  Tarefa;

---

#### Feedback (Mateus O. Patrício e Gabriel Bonifácio)
- [ ]  Colocar mais informações na introdução (está muito breve);
- [ ]  Buscar trazer um maior embasamento na literatura;
- [ ]  Criar uma seção dedicada a Metodologia, respeitando a padronização de documentação (deixar como o template do Diagrama de Classes, por exemplo);
- [ ] Disponibilizar mais versões do diagrama;
- [ ] Falta texto, complementando o nível de modelagem.
- [ ] Adicionar elos a outros artefatos;
- [ ] Rastros para os debates em equipe (caso haja);
- [ ] Sem referência sendo acordada no texto. Seria adequado, conferindo maior embasamento à escrita.
- [ ] Adicionar mais referências e corrigir o link delas (as 2 estão não clicáveis);
- [ ] Adicionar mais pessoas na produção da documentação.
#### Adicionais
- [ ] Alterar palavras de português para inglês.

---

#### Feedback (João Pedro e Edson)

- [x]  Buscar trazer um maior embasamento na literatura;
- [x]  Buscar criar elos com artefatos terceiros;
- [x] Buscar citar referências no texto (embasamento à escrita);
- [ ] Buscar padronizar template da especificação;
- [ ] Uso de gateways. Incluir semântica;
- [ ] Usar abstrações mais refinadas, tais como: raias, bifurcações e uniões;
- [ ] Rastros para os debates em equipe;
- [ ] Adicionar explicações complementares;
- [x] Adicionar mais referências bibliográficas.

#### Adicionais
- [ ]  Tarefa;

---

#### Feedback (João Pedro)
- [x]  Colocar mais embasamento na literatura na introdução;
- [ ]  Adicionar elos com terceiros;
- [x]  Adicionar referência no texto;
- [x]  Padronizar diagramas de acordo com template da especificação;
- [x]  Colocar parâmetros, caso existam, nos métodos apresentados nos diagramas;
- [ ]  Adicionar explicações complementares sobre os diagramas;
- [ ]  Adicionar rastros para debates em equipe, caso haja.
#### Adicionais
- [ ]  Tarefa;

---

###### Todos os diagramas:
- [x] Nem todos os estados estão especificados da forma correta. Há estados especificados corretamente, tais como: Fazendo login, e Fazendo cadastro. Entretanto, há outros que parecem atividades, e não estados, tais como: Comunicar com o Centro Educacional ou Acessar o chat da aplicação;
- [x] Não usam abstrações mais refinadas, tais como: Fork, Join, e estados com compartimentos internos.
- [ ] Sem explicações complementares;

###### Diagrama 3
- [x]  Deve-se rever também o estado Deletando turma/evento para Removendo turma/evento;

#### Adicionais
- [x]  Tarefa;

---

#### Feedback (Enzo Gabriel e Edson Soares)
- [x]  Buscar trazer um maior embasamento na literatura;
- [x] Buscar criar elos com artefatos terceiros;
- [x] Buscar citar referências no texto (embasamento à escrita);
- [x] Buscar padronizar template da especificação;
- [x] Criar mais diagramas para representar outros fluxos (temos apenas dois);
- [x] Usar entidade. Por exemplo: ---->  :Admin, :UserController, e :Teacher;
- [x] Usar stereotype <<view>>, na especificação da tela;
- [x] Adicionar explicações complementares;
- [x] Rastros para os debates em equipe;
- [x] Especificar Pais/Responsáveis em inglês, mantendo o padrão;
- [x] Fazer mais versionamentos.

#### Adicionais:
- [x]  Tarefa;
---

#### Feedback (Daniel Porto, Francisco Emanoel)
- [x] Buscar trazer um maior embasamento na literatura;
- [x] Buscar criar elos com artefatos terceiros;
- [x] Buscar citar referências no texto (embasamento à escrita);
- [ ] Referenciar o padrão CamelCase;

#### Adicionais
- [ ]  Tarefa;

---

#### Feedback (Edson Soares, Eliseu Kadesh, Daniel Porto)
não se aplica
#### Adicionais
- [x] Atualizar o diagrama de acordo com o que foi desenvolvido na modelagem física;

---

#### Feedback (Nilo Mendonça)
- [ ] Usar os stereotypes: < < include > > e < < extends > >. Não usar em português;
#### Adicionais

---
### Critérios de aceitação:
- [ ] Issue ser pontuada;
- [ ] Todos os diagramas serem revisados perante o feedback da Entrega 2;
- [ ] Todos os diagramas serem atualizados perante o desenvolvimento dos GRASP E GOFS.

**Comment by edsondearaujo** [comment]
### Obs

- No diagrama de sequência responsável fazendo login, seria interessante adicionar a camada MODEL.

**Comment by edsondearaujo** [comment]
### Diagrama de atividades
- Tarefas realizadas na revisão da issue #161 

- [ ] Buscar trazer um maior embasamento na literatura;
- [ ] Buscar criar elos com artefatos terceiros;
- [ ] Buscar citar referências no texto (embasamento à escrita);
- [ ] Adicionar mais referências bibliográfica.

**Comment by edsondearaujo** [comment]
***Atenção*** <br> Os ajustes relacionados a parte do embasamento teórico dos Diagramas: Classes, Atividades, Sequência e DER. Foram feitos na issue #161
