### ISSUE TITLE
Desenvolver Roadmap

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#58]
### Descrição:
Descrição do Issue.

### Tarefas:
- [ ] Estudar todos os artefatos base que terão que ser entregues em cada entrega;
- [ ] Mostrar aos membros o Roadmap.

### Critérios de aceitação:
- [ ] Todos os concordarem com o Readmap levantado;
- [ ] Todas entregas de artefatos tem que ser contempladas;
- [x] Todos os integrantes derem suas pontuações no Planning Poker.

**Comment by Bruno-Felix** [comment]
Devido a seleção não previsível de entregas, optamos somente por inserir Roadmap quando iniciarmos o planejamento do desenvolvimento.
